#!/bin/sh -x
#	$OpenBSD: checkflist,v 1.3 2003/04/07 16:24:06 todd Exp $

if [ "X${DESTDIR}" = "X" ]; then
	echo DESTDIR must be set
	exit 1
fi

Release=$1


TMP=`mktemp -d /tmp/_xckr.XXXXXX` || exit 1
trap 'rm -rf $TMP' 0 1 15

sh makeflist $Release > $TMP/_CHECK
( cd $DESTDIR ; find . \( -type d -o -type f -o -type l \) ) | sort | \
    diff -u $TMP/_CHECK -
