#!/bin/sh
#	$OpenBSD: genlists,v 1.1 2004/11/11 23:01:11 todd Exp $

arch=$1
lists="xbase xetc xserv xshare xfont"

l=""
for list in $lists  
do
	grep "$arch:$list" nocreate > /dev/null 2>&1 || l="$l $list"
done
echo $l
