#!/bin/sh
#	$OpenBSD: gensetlist,v 1.2 2003/04/12 16:32:05 todd Exp $

arch=$MACHINE
listsdir=`pwd`/lists

setname=$1
Release=$2

if [ "$setname" = "xfont" ]; then
        if [ "$arch" = "hp300" -o "$arch" = "pmax" ]; then
                arch=x11r5
        else
                arch=x11r6
        fi
fi


cat $listsdir/$setname/mi $listsdir/$setname/md.${arch} 
