#!/bin/sh
#	$OpenBSD: gensetlist,v 1.3 2004/11/11 23:01:11 todd Exp $

arch=$MACHINE
listsdir=`pwd`/lists

setname=$1
Release=$2

if [ "$setname" = "xfont" ]; then
        if [ "$arch" = "hp300" ]; then
                arch=x11r5
        else
                arch=x11r6
        fi
fi


cat $listsdir/$setname/mi $listsdir/$setname/md.${arch} 
