#!/bin/sh
#	$OpenBSD: gensetlist,v 1.4 2005/01/26 18:41:59 miod Exp $

arch=$MACHINE
listsdir=`pwd`/lists

setname=$1
Release=$2

if [ "$setname" = "xfont" ]; then
        arch=x11r6
fi

cat $listsdir/$setname/mi $listsdir/$setname/md.${arch} 
