#!/bin/sh
#	$OpenBSD: makeflist,v 1.8 2004/11/11 23:01:11 todd Exp $

arch=$MACHINE
Release=$1
listsdir=`pwd`/lists

lists=`sh ./genlists $arch`
for setname in $lists
do
	sh ./gensetlist $setname $Release
done | sort
