#!/bin/sh
#	$OpenBSD: makeflist,v 1.7 2004/06/22 00:37:34 matthieu Exp $

arch=$MACHINE
Release=$1
listsdir=`pwd`/lists

lists="xbase xetc xserv xshare"

if [ "$arch" != "vax" ]; then
	lists="$lists xfont"
fi

for setname in $lists
do
	sh ./gensetlist $setname $Release
done | sort
