#!/bin/sh
#	$OpenBSD: maketars,v 1.10 2004/12/09 06:15:41 todd Exp $

# xy
RELEASE=$1
Release=$2
# x.y

if [ "X${RELEASE}" = "X" ]; then
	echo "Usage: `basename $0` <OSREVISION>"
	exit 1
fi

if [ "X${RELEASEDIR}" = "X" ]; then
	echo RELEASEDIR must be set
	exit 1
fi

if [ "X${DESTDIR}" = "X" ]; then
	echo DESTDIR must be set
	exit 1
fi

arch=${MACHINE}
pwd=`pwd`
listsdir=`pwd`/lists
tardir=$RELEASEDIR

lists=`sh ./genlists $arch`

cd $DESTDIR

for setname in $lists; do
	echo -n "${setname}: "
	(cd $pwd; sh gensetlist $setname $Release) | sort | \
	    pax -w -d | gzip -9 > ${tardir}/${setname}${RELEASE}.tgz
	echo    "done."
done

echo    "done."
