#!/bin/sh
#	$OpenBSD: makeflist,v 1.6 2003/11/24 19:01:16 mickey Exp $

arch=$MACHINE
Release=$1
listsdir=`pwd`/lists

lists="xbase xserv xshare"

if [ "$arch" != "vax" ]; then
	lists="$lists xfont"
fi

for setname in $lists
do
	sh ./gensetlist $setname $Release
done | sort
