#!/bin/sh
#
# $OpenBSD: Startup_0,v 1.2 2004/02/13 22:57:39 matthieu Exp $
#
# Xstartup
#       This program is run as root after the user is verified
#
if [ -f /etc/nologin ]; then
        /usr/X11R6/bin/xmessage -file /etc/nologin -timeout 30 -center
        exit 1
fi
# sessreg not necessary?
/usr/X11R6/lib/X11/xdm/GiveConsole
exit 0
