#!/bin/sh
# Reassign ownership of the console to root, this should disallow
# assignment of console output to any random users's xterm
# $Xorg: TakeConsole,v 1.3 2000/08/17 19:54:17 cpqbld Exp $
# $OpenBSD: TakeConsole,v 1.3 2004/11/03 00:22:21 matthieu Exp $
#
chmod 622 /dev/console
chown root /dev/console
/usr/X11R6/bin/sessreg -d -l $DISPLAY -u /var/run/utmp -x /usr/X11R6/lib/X11/xdm/Xservers $USER
