#!/bin/sh
# $XConsortium: Xsession /main/10 1995/12/18 18:21:28 gildea $

# redirect errors to a file in user's home directory if we can
for errfile in "$HOME/.xsession-errors" "${TMPDIR-/tmp}/xses-$USER" "/tmp/xses-$USER"
do
	case "$errfile" in
	/tmp/* | /var/tmp/*)
		errfile=`mktemp ${errfile}.XXXXXX` || break;
		;;
	esac
	if ( cp /dev/null "$errfile" 2> /dev/null )
	then
		chmod 600 "$errfile"
		exec > "$errfile" 2>&1
		break
	fi
done

# if we have private ssh key(s), start ssh-agent and add the key(s)
id1=$HOME/.ssh/identity
id2=$HOME/.ssh/id_dsa
id3=$HOME/.ssh/id_rsa
if [ -e /usr/bin/ssh-agent ] && [ -f $id1 -o -f $id2 -o -f $id3 ];
then
	eval `ssh-agent -s`
	for f in $id1 $id2 $id3; do
		[ -f $f ] && ssh-add $f < /dev/null
	done
fi

do_exit() {
	if [ "$SSH_AGENT_PID" ]; then
		ssh-add -D < /dev/null
		eval `ssh-agent -s -k`
	fi
	exit
}

case $# in
1)
	case $1 in
	failsafe)
		xterm -geometry 80x24-0-0
		do_exit
		;;
	esac
esac

startup=$HOME/.xsession
resources=$HOME/.Xresources

if [ -f "$startup" ]; then
	"$startup"
	do_exit
else
	if [ -f "$resources" ]; then
		xrdb -load "$resources"
	fi
	xterm &
	fvwm
	do_exit
fi
