#!/bin/sh
# 
# $OpenBSD: Xstartup,v 1.1 2006/01/21 22:12:12 matthieu Exp $
#
# Register a login (derived from GiveConsole as follows:)
#
if [ -f /etc/nologin ]; then
        /usr/X11R6/bin/xmessage -file /etc/nologin -timeout 30 -center
        exit 1
fi
/usr/X11R6/bin/sessreg  -a -w "/var/log/wtmp" -u "/var/run/utmp" \
	-x "/etc/X11/xdm/Xservers" -l $DISPLAY -h "" $USER
